product_1 = Product.create!(name: 'Small bagel box (12 plain)', description: 'plain bagels', price: 12.00, product_type: 'c')
product_2 = Product.create!(name: 'Small bagel box (12 variety of 2 each)', description: '2 each of plain, sesame seed, poppy seed, onion, whole wheat, cinnamon raisin', price: 15.00, product_type: 'c')
product_3 = Product.create!(name: 'Small bagel box (12 any variety)', description: '12 of any one variety: plain, sesame seed, poppy seed, onion, whole wheat, cinnamon raisin ', price: 15.00, product_type: 'c')
product_4 = Product.create!(name: 'Large bagel box (18 plain)', description: 'plain bagels', price: 18.00, product_type: 'c')
product_5 = Product.create!(name: 'Large bagel box (18 variety of 3 each)', description: '3 each of plain, sesame seed, poppy seed, onion, whole wheat, cinnamon raisin ', price: 20.00, product_type: 'c')
product_6 = Product.create!(name: 'Large bagel box (18 any variety)', description: '18 of any one variety', price: 2000, product_type: 'c')
product_7 = Product.create!(name: 'Cream Cheese (catering size)', description: 'plain', price: 4.00, product_type: 'c')
product_8 = Product.create!(name: 'Cream Cheese (catering size)', description: 'chive', price: 4.50, product_type: 'c')
product_9 = Product.create!(name: 'Cream Cheese (catering size)', description: 'tofutti (vegetarian)', price: 4.50, product_type: 'c')
product_10 = Product.create!(name: 'Cream Cheese (catering size)', description: 'salmon spread', price: 5.50, product_type: 'c')
product_11 = Product.create!(name: 'Party Box', description: '25 bagels plus plain and chive cream cheese', price: 50.00, product_type: 'c')
product_12 = Product.create!(name: 'The Somerville', description: 'whole wheat bagel with avocado, tomato, cucumber, sprouts, tofutti cream cheese', price: 6.75, product_type: 'a')
product_13 = Product.create!(name: 'The North End', description: 'onion bagel with roast beef, tomato, red onions, asiago cheese, provolone cheese', price: 6.50, product_type: 'a')
product_14 = Product.create!(name: 'The South End', description: 'sesame bagel with corn beef, cole slaw, swiss cheese, spicy mustard', price: 6.50, product_type: 'a')
product_15 = Product.create!(name: 'The Hub', description: 'plain bagel with turkey, garlic mayonaisse, tomato, cucumber, sprouts', price: 6.00, product_type: 'a')
product_16 = Product.create!(name: 'The Brookline', description: 'poppyseed bagel with cream cheese, tomato, red onions, smoked salmon', price: 7.50, product_type: 'a')
product_17 = Product.create!(name: 'Fountain Soda small', description: 'Coke', price: 2.75, product_type: 'd')
product_18 = Product.create!(name: 'Fountain Soda small', description: 'Diet Coke', price: 2.75, product_type: 'd')
product_19 = Product.create!(name: 'Fountain Soda small', description: 'Sprite', price: 2.75, product_type: 'd')
product_20 = Product.create!(name: 'Fountain Soda large', description: 'Coke', price: 3.50, product_type: 'd')
product_21 = Product.create!(name: 'Fountain Soda large', description: 'Diet Coke', price: 3.50, product_type: 'd')
product_22 = Product.create!(name: 'Fountain Soda large', description: 'Sprite', price: 3.50, product_type: 'd')
product_23 = Product.create!(name: 'Hot Coffee small', description: 'best hot coffee in town', price: 2.00, product_type: 'd')
product_24 = Product.create!(name: 'Hot Coffee large', description: 'best hot coffee in town', price: 2.50, product_type: 'd')
product_25 = Product.create!(name: 'Latte small', description: 'voted best latte 2014', price: 3.50, product_type: 'd')
product_26 = Product.create!(name: 'Latte large', description: 'voted best latte 2014', price: 4.25, product_type: 'd')

product_27 = Product.create!(name: 'Build Your Own Bagel!', description: 'plain bagel - customize it yourself', price: 250, product_type: 'b')
product_28 = Product.create!(name: 'Build Your Own Bagel!', description: 'variety bagel - customize it yourself', price: 300, product_type: 'b')

Ingredient.create!(name: 'tomato', price: 0.00)
Ingredient.create!(name: 'cucumber', price: 0.00)
Ingredient.create!(name: 'red onions', price: 0.00)
Ingredient.create!(name: 'cole slaw', price: 0.00)
Ingredient.create!(name: 'mayo', price: 0.50)
Ingredient.create!(name: 'garlic mayo', price: 0.50)
Ingredient.create!(name: 'mustard', price: 0.50)
Ingredient.create!(name: 'spicy mustard', price: 0.50)
Ingredient.create!(name: 'plain cream cheese', price: 1.50)
Ingredient.create!(name: 'chive cream cheese', price: 1.50)
Ingredient.create!(name: 'tofutti', price: 2.00)
Ingredient.create!(name: 'salmon spread', price: 2.50)
Ingredient.create!(name: 'asiago', price: 0.50)
Ingredient.create!(name: 'provolone', price: 0.50)
Ingredient.create!(name: 'swiss', price: 0.50)
Ingredient.create!(name: 'cheddar cheese', price: 0.50)
Ingredient.create!(name: 'avocado', price: 2.00)
Ingredient.create!(name: 'sprouts', price: 0.50)
Ingredient.create!(name: 'turkey', price: 2.00)
Ingredient.create!(name: 'smoked salmon', price: 3.50)
Ingredient.create!(name: 'roast beef', price: 2.00)
Ingredient.create!(name: 'corn beef', price: 3.00)
