IngredientsInProduct.delete_all
Product.delete_all
Ingredient.delete_all


prod_1 = Product.create!(name: 'Small bagel box (12 plain)', description: 'plain bagels', price: 12.00, product_type: 'c')
prod_2 = Product.create!(name: 'Small bagel box (12 variety of 2 each)', description: '2 each of plain, sesame seed, poppy seed, onion, whole wheat, cinnamon raisin', price: 15.00, product_type: 'c')
prod_3 = Product.create!(name: 'Small bagel box (12 any variety)', description: '12 of any one variety: plain, sesame seed, poppy seed, onion, whole wheat, cinnamon raisin ', price: 15.00, product_type: 'c')
prod_4 = Product.create!(name: 'Large bagel box (18 plain)', description: 'plain bagels', price: 18.00, product_type: 'c')
prod_5 = Product.create!(name: 'Large bagel box (18 variety of 3 each)', description: '3 each of plain, sesame seed, poppy seed, onion, whole wheat, cinnamon raisin ', price: 20.00, product_type: 'c')
prod_6 = Product.create!(name: 'Large bagel box (18 any variety)', description: '18 of any one variety', price: 2000, product_type: 'c')
prod_7 = Product.create!(name: 'Cream Cheese (catering size)', description: 'plain', price: 4.00, product_type: 'c')
prod_8 = Product.create!(name: 'Cream Cheese (catering size)', description: 'chive', price: 4.50, product_type: 'c')
prod_9 = Product.create!(name: 'Cream Cheese (catering size)', description: 'tofutti (vegetarian)', price: 4.50, product_type: 'c')
prod_10 = Product.create!(name: 'Cream Cheese (catering size)', description: 'salmon spread', price: 5.50, product_type: 'c')
prod_11 = Product.create!(name: 'Party Box', description: '25 bagels plus plain and chive cream cheese', price: 50.00, product_type: 'c')
prod_12 = Product.create!(name: 'The Somerville', description: 'whole wheat bagel with avocado, tomato, cucumber, sprouts, tofutti cream cheese', price: 6.75, product_type: 'a')
prod_13 = Product.create!(name: 'The North End', description: 'onion bagel with roast beef, tomato, red onions, asiago cheese, provolone cheese', price: 6.50, product_type: 'a')
prod_14 = Product.create!(name: 'The South End', description: 'sesame bagel with corn beef, cole slaw, swiss cheese, spicy mustard', price: 6.50, product_type: 'a')
prod_15 = Product.create!(name: 'The Hub', description: 'plain bagel with turkey, garlic mayonaisse, tomato, cucumber, sprouts', price: 6.00, product_type: 'a')
prod_16 = Product.create!(name: 'The Brookline', description: 'poppyseed bagel with cream cheese, tomato, red onions, smoked salmon', price: 7.50, product_type: 'a')
prod_17 = Product.create!(name: 'Fountain Soda small', description: 'Coke', price: 2.75, product_type: 'd')
prod_18 = Product.create!(name: 'Fountain Soda small', description: 'Diet Coke', price: 2.75, product_type: 'd')
prod_19 = Product.create!(name: 'Fountain Soda small', description: 'Sprite', price: 2.75, product_type: 'd')
prod_20 = Product.create!(name: 'Fountain Soda large', description: 'Coke', price: 3.50, product_type: 'd')
prod_21 = Product.create!(name: 'Fountain Soda large', description: 'Diet Coke', price: 3.50, product_type: 'd')
prod_22 = Product.create!(name: 'Fountain Soda large', description: 'Sprite', price: 3.50, product_type: 'd')
prod_23 = Product.create!(name: 'Hot Coffee small', description: 'best hot coffee in town', price: 2.00, product_type: 'd')
prod_24 = Product.create!(name: 'Hot Coffee large', description: 'best hot coffee in town', price: 2.50, product_type: 'd')
prod_25 = Product.create!(name: 'Latte small', description: 'voted best latte 2014', price: 3.50, product_type: 'd')
prod_26 = Product.create!(name: 'Latte large', description: 'voted best latte 2014', price: 4.25, product_type: 'd')

prod_27 = Product.create!(name: 'Build Your Own Bagel!', description: 'plain bagel - customize it yourself', price: 250, product_type: 'b')
prod_28 = Product.create!(name: 'Build Your Own Bagel!', description: 'variety bagel - customize it yourself', price: 300, product_type: 'b')

Ingredient.create!(name: 'tomato', price: 0.00)
Ingredient.create!(name: 'cucumber', price: 0.00)
Ingredient.create!(name: 'red onions', price: 0.00)
Ingredient.create!(name: 'cole slaw', price: 0.00)
Ingredient.create!(name: 'mayo', price: 0.50)
Ingredient.create!(name: 'garlic mayo', price: 0.50)
Ingredient.create!(name: 'mustard', price: 0.50)
Ingredient.create!(name: 'spicy mustard', price: 0.50)
Ingredient.create!(name: 'plain cream cheese', price: 1.50)
Ingredient.create!(name: 'chive cream cheese', price: 1.50)
Ingredient.create!(name: 'tofutti', price: 2.00)
Ingredient.create!(name: 'salmon spread', price: 2.50)
Ingredient.create!(name: 'asiago', price: 0.50)
Ingredient.create!(name: 'provolone', price: 0.50)
Ingredient.create!(name: 'swiss', price: 0.50)
Ingredient.create!(name: 'cheddar cheese', price: 0.50)
Ingredient.create!(name: 'avocado', price: 2.00)
Ingredient.create!(name: 'sprouts', price: 0.50)
Ingredient.create!(name: 'turkey', price: 2.00)
Ingredient.create!(name: 'smoked salmon', price: 3.50)
Ingredient.create!(name: 'roast beef', price: 2.00)
Ingredient.create!(name: 'corn beef', price: 3.00)

ingr_in_prod_1 = IngredientsInProduct.create!(product_id: 1, ingredient_id: 1)
ingr_in_prod_2 = IngredientsInProduct.create!(product_id: 1, ingredient_id: 2)
ingr_in_prod_3 = IngredientsInProduct.create!(product_id: 1, ingredient_id: 3)
ingr_in_prod_4 = IngredientsInProduct.create!(product_id: 1, ingredient_id: 4)
ingr_in_prod_5 = IngredientsInProduct.create!(product_id: 1, ingredient_id: 5)
ingr_in_prod_6 = IngredientsInProduct.create!(product_id: 1, ingredient_id: 6)
ingr_in_prod_7 = IngredientsInProduct.create!(product_id: 1, ingredient_id: 7)
ingr_in_prod_8 = IngredientsInProduct.create!(product_id: 1, ingredient_id: 8)
ingr_in_prod_9 = IngredientsInProduct.create!(product_id: 1, ingredient_id: 9)
ingr_in_prod_10  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 10)
ingr_in_prod_11  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 11)
ingr_in_prod_12  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 12)
ingr_in_prod_13  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 13)
ingr_in_prod_14  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 14)
ingr_in_prod_15  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 15)
ingr_in_prod_16  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 16)
ingr_in_prod_17  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 17)
ingr_in_prod_18  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 18)
ingr_in_prod_19  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 19)
ingr_in_prod_20  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 20)
ingr_in_prod_21  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 21)
ingr_in_prod_22  = IngredientsInProduct.create!(product_id: 1, ingredient_id: 22)

ingr_in_prod_23  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 1)
ingr_in_prod_24  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 2)
ingr_in_prod_25  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 3)
ingr_in_prod_26  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 4)
ingr_in_prod_27  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 5)
ingr_in_prod_28  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 6)
ingr_in_prod_29  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 7)
ingr_in_prod_30  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 8)
ingr_in_prod_31  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 9)
ingr_in_prod_32  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 10)
ingr_in_prod_33  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 11)
ingr_in_prod_34  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 12)
ingr_in_prod_35  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 13)
ingr_in_prod_36  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 14)
ingr_in_prod_37  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 15)
ingr_in_prod_38  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 16)
ingr_in_prod_39  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 17)
ingr_in_prod_40  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 18)
ingr_in_prod_41  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 19)
ingr_in_prod_42  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 20)
ingr_in_prod_43  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 21)
ingr_in_prod_44  = IngredientsInProduct.create!(product_id: 2, ingredient_id: 22)

ingr_in_prod_45  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 1)
ingr_in_prod_46  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 2)
ingr_in_prod_47  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 3)
ingr_in_prod_48  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 4)
ingr_in_prod_49  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 5)
ingr_in_prod_50  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 6)
ingr_in_prod_51  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 7)
ingr_in_prod_52  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 8)
ingr_in_prod_53  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 9)
ingr_in_prod_54  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 10)
ingr_in_prod_55  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 11)
ingr_in_prod_56  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 12)
ingr_in_prod_57  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 13)
ingr_in_prod_58  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 14)
ingr_in_prod_59  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 15)
ingr_in_prod_60  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 16)
ingr_in_prod_61  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 17)
ingr_in_prod_62  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 18)
ingr_in_prod_63  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 19)
ingr_in_prod_64  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 20)
ingr_in_prod_65  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 21)
ingr_in_prod_66  = IngredientsInProduct.create!(product_id: 3, ingredient_id: 22)

ingr_in_prod_67  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 1)
ingr_in_prod_68  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 2)
ingr_in_prod_69  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 3)
ingr_in_prod_70  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 4)
ingr_in_prod_71  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 5)
ingr_in_prod_72  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 6)
ingr_in_prod_73  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 7)
ingr_in_prod_74  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 8)
ingr_in_prod_75  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 9)
ingr_in_prod_76  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 10)
ingr_in_prod_77  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 11)
ingr_in_prod_78  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 12)
ingr_in_prod_79  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 13)
ingr_in_prod_80  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 14)
ingr_in_prod_81  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 15)
ingr_in_prod_82  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 16)
ingr_in_prod_83  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 17)
ingr_in_prod_84  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 18)
ingr_in_prod_85  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 19)
ingr_in_prod_86  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 20)
ingr_in_prod_87  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 21)
ingr_in_prod_88  = IngredientsInProduct.create!(product_id: 4, ingredient_id: 22)

ingr_in_prod_89  = IngredientsInProduct.create!(product_id: 5, ingredient_id: 1)
ingr_in_prod_90  = IngredientsInProduct.create!(product_id: 5, ingredient_id: 2)
ingr_in_prod_91  = IngredientsInProduct.create!(product_id: 5, ingredient_id: 3)
ingr_in_prod_92  = IngredientsInProduct.create!(product_id: 5, ingredient_id: 4)
ingr_in_prod_93  = IngredientsInProduct.create!(product_id: 5, ingredient_id: 5)
ingr_in_prod_94  = IngredientsInProduct.create!(product_id: 5, ingredient_id: 6)
ingr_in_prod_95  = IngredientsInProduct.create!(product_id: 5, ingredient_id: 7)
ingr_in_prod_96  = IngredientsInProduct.create!(product_id: 5, ingredient_id: 8)
ingr_in_prod_97  = IngredientsInProduct.create!(product_id: 5, ingredient_id: 9)
ingr_in_prod_98  = IngredientsInProduct.create!(product_id: 5, ingredient_id: 10)
ingr_in_prod_99  = IngredientsInProduct.create!(product_id: 5, ingredient_id: 11)
ingr_in_prod_100 = IngredientsInProduct.create!(product_id: 5, ingredient_id: 12)
ingr_in_prod_101 = IngredientsInProduct.create!(product_id: 5, ingredient_id: 13)
ingr_in_prod_102 = IngredientsInProduct.create!(product_id: 5, ingredient_id: 14)
ingr_in_prod_103 = IngredientsInProduct.create!(product_id: 5, ingredient_id: 15)
ingr_in_prod_104 = IngredientsInProduct.create!(product_id: 5, ingredient_id: 16)
ingr_in_prod_105 = IngredientsInProduct.create!(product_id: 5, ingredient_id: 17)
ingr_in_prod_106 = IngredientsInProduct.create!(product_id: 5, ingredient_id: 18)
ingr_in_prod_107 = IngredientsInProduct.create!(product_id: 5, ingredient_id: 19)
ingr_in_prod_108 = IngredientsInProduct.create!(product_id: 5, ingredient_id: 20)
ingr_in_prod_109 = IngredientsInProduct.create!(product_id: 5, ingredient_id: 21)
ingr_in_prod_110 = IngredientsInProduct.create!(product_id: 5, ingredient_id: 22)

ingr_in_prod_111 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 1)
ingr_in_prod_112 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 2)
ingr_in_prod_113 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 3)
ingr_in_prod_114 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 4)
ingr_in_prod_115 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 5)
ingr_in_prod_116 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 6)
ingr_in_prod_117 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 7)
ingr_in_prod_118 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 8)
ingr_in_prod_119 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 9)
ingr_in_prod_120 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 10)
ingr_in_prod_121 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 11)
ingr_in_prod_122 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 12)
ingr_in_prod_123 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 13)
ingr_in_prod_124 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 14)
ingr_in_prod_125 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 15)
ingr_in_prod_126 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 16)
ingr_in_prod_127 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 17)
ingr_in_prod_128 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 18)
ingr_in_prod_129 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 19)
ingr_in_prod_130 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 20)
ingr_in_prod_131 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 21)
ingr_in_prod_132 = IngredientsInProduct.create!(product_id: 6, ingredient_id: 22)

ingr_in_prod_133 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 1)
ingr_in_prod_134 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 2)
ingr_in_prod_135 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 3)
ingr_in_prod_136 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 4)
ingr_in_prod_137 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 5)
ingr_in_prod_138 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 6)
ingr_in_prod_139 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 7)
ingr_in_prod_140 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 8)
ingr_in_prod_141 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 9)
ingr_in_prod_142 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 10)
ingr_in_prod_143 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 11)
ingr_in_prod_144 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 12)
ingr_in_prod_145 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 13)
ingr_in_prod_146 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 14)
ingr_in_prod_147 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 15)
ingr_in_prod_148 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 16)
ingr_in_prod_149 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 17)
ingr_in_prod_150 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 18)
ingr_in_prod_151 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 19)
ingr_in_prod_152 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 20)
ingr_in_prod_153 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 21)
ingr_in_prod_154 = IngredientsInProduct.create!(product_id: 7, ingredient_id: 22)

ingr_in_prod_155 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 1)
ingr_in_prod_156 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 2)
ingr_in_prod_157 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 3)
ingr_in_prod_158 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 4)
ingr_in_prod_159 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 5)
ingr_in_prod_160 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 6)
ingr_in_prod_161 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 7)
ingr_in_prod_162 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 8)
ingr_in_prod_163 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 9)
ingr_in_prod_164 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 10)
ingr_in_prod_165 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 11)
ingr_in_prod_166 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 12)
ingr_in_prod_167 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 13)
ingr_in_prod_168 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 14)
ingr_in_prod_169 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 15)
ingr_in_prod_170 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 16)
ingr_in_prod_171 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 17)
ingr_in_prod_172 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 18)
ingr_in_prod_173 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 19)
ingr_in_prod_174 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 20)
ingr_in_prod_175 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 21)
ingr_in_prod_176 = IngredientsInProduct.create!(product_id: 8, ingredient_id: 22)

ingr_in_prod_177 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 1)
ingr_in_prod_178 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 2)
ingr_in_prod_179 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 3)
ingr_in_prod_180 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 4)
ingr_in_prod_181 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 5)
ingr_in_prod_182 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 6)
ingr_in_prod_183 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 7)
ingr_in_prod_184 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 8)
ingr_in_prod_185 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 9)
ingr_in_prod_186 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 10)
ingr_in_prod_187 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 11)
ingr_in_prod_188 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 12)
ingr_in_prod_189 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 13)
ingr_in_prod_190 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 14)
ingr_in_prod_191 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 15)
ingr_in_prod_192 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 16)
ingr_in_prod_193 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 17)
ingr_in_prod_194 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 18)
ingr_in_prod_195 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 19)
ingr_in_prod_196 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 20)
ingr_in_prod_197 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 21)
ingr_in_prod_198 = IngredientsInProduct.create!(product_id: 9, ingredient_id: 22)

ingr_in_prod_199 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 1)
ingr_in_prod_200 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 2)
ingr_in_prod_201 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 3)
ingr_in_prod_202 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 4)
ingr_in_prod_203 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 5)
ingr_in_prod_204 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 6)
ingr_in_prod_205 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 7)
ingr_in_prod_206 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 8)
ingr_in_prod_207 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 9)
ingr_in_prod_208 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 10)
ingr_in_prod_209 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 11)
ingr_in_prod_210 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 12)
ingr_in_prod_211 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 13)
ingr_in_prod_212 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 14)
ingr_in_prod_213 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 15)
ingr_in_prod_214 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 16)
ingr_in_prod_215 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 17)
ingr_in_prod_216 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 18)
ingr_in_prod_217 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 19)
ingr_in_prod_218 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 20)
ingr_in_prod_219 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 21)
ingr_in_prod_220 = IngredientsInProduct.create!(product_id: 10 , ingredient_id: 22)
